default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: helpmycode_development

test:
  <<: *default
  database: helpmycode_test

production:
  <<: *default
  database: helpmycode_production
  username: helpmycode
  password: <%= ENV['HELPMYCODE_DATABASE_PASSWORD'] %>

<%= IO.read('config/database.local.yml') if File.exists?('config/database.local.yml') %>
